AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda (Ingest) → SQS → Lambda (Metadata Extractor) → S3

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures: [x86_64]

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub images-${AWS::AccountId}-${AWS::Region}

  MetadataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "metadata-queue"
      VisibilityTimeout: 300  # 5 minutes (Matches or exceeds Lambda timeout)
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 5    # Move to DLQ after 5 failed attempts

  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "my-app-dlq"                        

  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: metadata.lambda_handler
      Environment:
        Variables:
          INPUT_PREFIX: incoming/
          OUTPUT_PREFIX: grayscale/
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub images-${AWS::AccountId}-${AWS::Region}
      Events:
        ImageUpload:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: incoming/

  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
